// Estratto da HabboAirLauncher.deobf.js, riga 66982.
// Corrisponde a AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/core/window/utils/class_2715.as
// Nome offuscato: _i184c4676325470

class extends class_2090 {
  static {
    n(this, "class_2715");
  }
  static fillTables(e, r = null) {
    if (
      ((e.background = class_2090.const_583),
      (e.bitmap = class_2090.WINDOW_TYPE_BITMAP_WRAPPER),
      (e.bitmap_fill = class_2090.const_213),
      (e.border = class_2090.WINDOW_TYPE_BORDER),
      (e.boxsizer = class_2090.WINDOW_TYPE_BOXSIZER),
      (e.border_notify = class_2090.const_1071),
      (e.bubble = class_2090.const_381),
      (e.bubble_pointer_up = class_2090.const_1028),
      (e.bubble_pointer_right = class_2090.WINDOW_TYPE_BUBBLE_POINTER_RIGHT),
      (e.bubble_pointer_down = class_2090.const_940),
      (e.bubble_pointer_left = class_2090.const_892),
      (e.button = class_2090.const_1305),
      (e.button_thick = class_2090.WINDOW_TYPE_BUTTON_THICK),
      (e.button_icon = class_2090.const_304),
      (e.button_group_left = class_2090.const_609),
      (e.button_group_center = class_2090.WINDOW_TYPE_BUTTON_GROUP_CENTER),
      (e.button_group_right = class_2090.WINDOW_TYPE_BUTTON_GROUP_RIGHT),
      (e.checkbox = class_2090.const_1039),
      (e.closebutton = class_2090.const_1381),
      (e.container = class_2090.WINDOW_TYPE_CONTAINER),
      (e.container_button = class_2090.const_675),
      (e.display_object_wrapper = class_2090.WINDOW_TYPE_DISPLAY_OBJECT_WRAPPER),
      (e.dropmenu = class_2090.WINDOW_TYPE_DROPMENU),
      (e.dropmenu_item = class_2090.const_696),
      (e.droplist = class_2090.WINDOW_TYPE_DROPLIST),
      (e.droplist_item = class_2090.const_1042),
      (e.formatted_text = class_2090.const_293),
      (e.frame = class_2090.WINDOW_TYPE_FRAME),
      (e.frame_notify = class_2090.const_318),
      (e.gradient = class_2090.const_1362),
      (e.header = class_2090.WINDOW_TYPE_HEADER),
      (e.html = class_2090.WINDOW_TYPE_HTML),
      (e.icon = class_2090.const_1172),
      (e.iconbutton = class_2090.const_336),
      (e.itemgrid = class_2090.WINDOW_TYPE_ITEMGRID),
      (e.itemgrid_horizontal = class_2090.WINDOW_TYPE_ITEMGRID_HORIZONTAL),
      (e.itemgrid_vertical = class_2090.WINDOW_TYPE_ITEMGRID_VERTICAL),
      (e.itemlist = class_2090._r60db056b5bffe9),
      (e.itemlist_horizontal = class_2090.WINDOW_TYPE_ITEMLIST_HORIZONTAL),
      (e.itemlist_vertical = class_2090._rb5e71f1a68d5e0),
      (e.label = class_2090.const_277),
      (e.maximizebox = class_2090.const_1122),
      (e.menu = class_2090.WINDOW_TYPE_MENU),
      (e.menu_item = class_2090.const_648),
      (e.submenu = class_2090.WINDOW_TYPE_SUBMENU),
      (e.minimizebox = class_2090.const_249),
      (e.notify = class_2090.const_1037),
      (e.null = class_2090.const_333),
      (e.password = class_2090.const_1114),
      (e.radiobutton = class_2090.const_326),
      (e.region = class_2090.const_1384),
      (e.restorebox = class_2090.const_1311),
      (e.scaler = class_2090.WINDOW_TYPE_SCALER),
      (e.scaler_horizontal = class_2090.WINDOW_TYPE_SCALER_HORIZONTAL),
      (e.scaler_vertical = class_2090.WINDOW_TYPE_SCALER_VERTICAL),
      (e.scrollbar_horizontal = class_2090.WINDOW_TYPE_SCROLLBAR_HORIZONTAL),
      (e.scrollbar_vertical = class_2090.WINDOW_TYPE_SCROLLBAR_VERTICAL),
      (e.scrollbar_slider_button_up = class_2090.const_279),
      (e.scrollbar_slider_button_down = class_2090.const_879),
      (e.scrollbar_slider_button_left = class_2090.const_560),
      (e.scrollbar_slider_button_right = class_2090.WINDOW_TYPE_SCROLLBAR_SLIDER_BUTTON_RIGHT),
      (e.scrollbar_slider_bar_horizontal = class_2090.WINDOW_TYPE_SCROLLBAR_SLIDER_BAR_HORIZONTAL),
      (e.scrollbar_slider_bar_vertical = class_2090.WINDOW_TYPE_SCROLLBAR_SLIDER_BAR_VERTICAL),
      (e.scrollbar_slider_track_horizontal = class_2090.WINDOW_TYPE_SCROLLBAR_SLIDER_TRACK_HORIZONTAL),
      (e.scrollbar_slider_track_vertical = class_2090.WINDOW_TYPE_SCROLLBAR_SLIDER_TRACK_VERTICAL),
      (e.scrollable_itemlist = class_2090.WINDOW_TYPE_SCROLLABLE_ITEMLIST),
      (e.scrollable_itemlist_vertical = class_2090.WINDOW_TYPE_SCROLLABLE_ITEMLIST_VERTICAL),
      (e.scrollable_itemgrid_vertical = class_2090.WINDOW_TYPE_SCROLLABLE_ITEMGRID_VERTICAL),
      (e.scrollable_itemlist_horizontal = class_2090.WINDOW_TYPE_SCROLLABLE_ITEMLIST_HORIZONTAL),
      (e.selector = class_2090.WINDOW_TYPE_SELECTOR),
      (e.selector_list = class_2090.WINDOW_TYPE_SELECTOR_LIST),
      (e.shape = class_2090.WINDOW_TYPE_SHAPE_WRAPPER),
      (e.static_bitmap = class_2090.WINDOW_TYPE_STATIC_BITMAP_WRAPPER),
      (e.stroke = class_2090.WINDOW_TYPE_STROKE),
      (e.tab_button = class_2090.const_1271),
      (e.tab_container_button = class_2090.const_944),
      (e.tab_context = class_2090.const_706),
      (e.tab_content = class_2090.WINDOW_TYPE_TAB_CONTENT),
      (e.tab_selector = class_2090.WINDOW_TYPE_TAB_SELECTOR),
      (e.text = class_2090.const_849),
      (e.input = class_2090.const_331),
      (e.link = class_2090.const_1191),
      (e.toolbar = class_2090.WINDOW_TYPE_TOOLBAR),
      (e.tooltip = class_2090.const_629),
      (e.widget = class_2090.WINDOW_TYPE_WIDGET),
      r != null)
    )
      for (let [t, i] of Object.entries(e)) r[i] = t;
  }
}
