// Extracted from HabboAirLauncher.deobf.js, line 181015.
// Matches AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/room/events/RoomObjectWidgetRequestEvent.as
// Obfuscated name: _i74b518e7373c0f

class extends RoomObjectEvent {
  static {
    n(this, "RoomObjectWidgetRequestEvent");
  }
  static ACHIEVEMENT_RESOLUTION_ENGRAVING = "ROWRE_ACHIEVEMENT_RESOLUTION_ENGRAVING";
  static ACHIEVEMENT_RESOLUTION_FAILED = "ROWRE_ACHIEVEMENT_RESOLUTION_FAILED";
  static ACHIEVEMENT_RESOLUTION_OPEN = "ROWRE_ACHIEVEMENT_RESOLUTION_OPEN";
  static BACKGROUND_COLOR = "ROWRE_BACKGROUND_COLOR";
  static BADGE_DISPLAY_ENGRAVING = "ROWRE_BADGE_DISPLAY_ENGRAVING";
  static CLOSE_FURNI_CONTEXT_MENU = "ROWRE_CLOSE_FURNI_CONTEXT_MENU";
  static CLOSE_WIDGET = "ROWRE_CLOSE_WIDGET";
  static CLOTHING_CHANGE = "ROWRE_CLOTHING_CHANGE";
  static CREDITFURNI = "ROWRE__CREDITFURNI";
  static DIMMER = "ROWRE_DIMMER";
  static ECOTRONBOX = "ROWRE_ECOTRONBOX";
  static const_446 = "ROWRE_EFFECTBOX_OPEN_DIALOG";
  static FRIEND_FURNITURE_CONFIRM = "ROWRE_FRIEND_FURNITURE_CONFIRM";
  static FRIEND_FURNITURE_ENGRAVING = "ROWRE_FRIEND_FURNITURE_ENGRAVING";
  static GUILD_FURNI_CONTEXT_MENU = "ROWRE_GUILD_FURNI_CONTEXT_MENU";
  static const_1303 = "ROWRE_HIDE_AREA";
  static const_662 = "ROWRE_HIDE_HIGH_SCORE_DISPLAY";
  static const_121 = "ROWRE_HIGH_SCORE_DISPLAY";
  static INTERNAL_LINK = "ROWRE_INTERNAL_LINK";
  static MANNEQUIN = "ROWRE_MANNEQUIN";
  static MONSTERPLANT_SEED_PLANT_CONFIRMATION_DIALOG = "ROWRE_MONSTERPLANT_SEED_PLANT_CONFIRMATION_DIALOG";
  static MYSTERYBOX_OPEN_DIALOG = "ROWRE_MYSTERYBOX_OPEN_DIALOG";
  static MYSTERYTROPHY_OPEN_DIALOG = "ROWRE_MYSTERYTROPHY_OPEN_DIALOG";
  static OPEN_FURNI_CONTEXT_MENU = "ROWRE_OPEN_FURNI_CONTEXT_MENU";
  static OPEN_WIDGET = "ROWRE_OPEN_WIDGET";
  static PET_PRODUCT_MENU = "ROWRE_PET_PRODUCT_MENU";
  static PLACEHOLDER = "ROWRE_PLACEHOLDER";
  static PLAYLIST_EDITOR = "ROWRE_JUKEBOX_PLAYLIST_EDITOR";
  static PRESENT = "ROWRE_PRESENT";
  static const_557 = "ROWRE_PURCHASABLE_CLOTHING_CONFIRMATION_DIALOG";
  static REMOVE_DIMMER = "ROWRE_WIDGET_REMOVE_DIMMER";
  static ROOM_LINK = "ROWRE_ROOM_LINK";
  static STICKIE = "ROWRE__STICKIE";
  static TEASER = "ROWRE_TEASER";
  static TROPHY = "ROWRE_TROPHY";
  constructor(e, r, t = !1, i = !1) {
    super(e, r, t, i);
  }
}
