// Estratto da HabboAirLauncher.deobf.js, riga 70384.
// Corrisponde a AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/room/events/RoomEngineToWidgetEvent.as
// Nome offuscato: _i9add70c0476873

class extends RoomEngineObjectEvent {
  constructor(r, t, i, s, o = null, d = !1, c = !1) {
    super(r, t, i, s, d, c);
    this.var_45 = o;
  }
  static {
    n(this, "RoomEngineToWidgetEvent");
  }
  static REQUEST_OPEN_WIDGET = "RETWE_OPEN_WIDGET";
  static REQUEST_CLOSE_WIDGET = "RETWE_CLOSE_WIDGET";
  static REQUEST_OPEN_FURNI_CONTEXT_MENU = "RETWE_OPEN_FURNI_CONTEXT_MENU";
  static REQUEST_CLOSE_FURNI_CONTEXT_MENU = "RETWE_CLOSE_FURNI_CONTEXT_MENU";
  static REQUEST_PLACEHOLDER = "RETWE_REQUEST_PLACEHOLDER";
  static REQUEST_CREDITFURNI = "RETWE_REQUEST_CREDITFURNI";
  static REQUEST_STICKIE = "RETWE_REQUEST_STICKIE";
  static REQUEST_PRESENT = "RETWE_REQUEST_PRESENT";
  static REQUEST_TROPHY = "RETWE_REQUEST_TROPHY";
  static REQUEST_TEASER = "RETWE_REQUEST_TEASER";
  static REQUEST_ECOTRONBOX = "RETWE_REQUEST_ECOTRONBOX";
  static REQUEST_DIMMER = "RETWE_REQUEST_DIMMER";
  static REMOVE_DIMMER = "RETWE_REMOVE_DIMMER";
  static REQUEST_CLOTHING_CHANGE = "RETWE_REQUEST_CLOTHING_CHANGE";
  static REQUEST_PLAYLIST_EDITOR = "RETWE_REQUEST_PLAYLIST_EDITOR";
  static REQUEST_MANNEQUIN = "RETWE_REQUEST_MANNEQUIN";
  static REQUEST_MONSTERPLANT_SEED_PLANT_CONFIRMATION_DIALOG = "ROWRE_REQUEST_MONSTERPLANT_SEED_PLANT_CONFIRMATION_DIALOG";
  static REQUEST_PURCHASABLE_CLOTHING_CONFIRMATION_DIALOG = "ROWRE_REQUEST_PURCHASABLE_CLOTHING_CONFIRMATION_DIALOG";
  static REQUEST_BACKGROUND_COLOR = "RETWE_REQUEST_BACKGROUND_COLOR";
  static REQUEST_AREA_HIDE = "RETWE_REQUEST_AREA_HIDE";
  static REQUEST_MYSTERYBOX_OPEN_DIALOG = "RETWE_REQUEST_MYSTERYBOX_OPEN_DIALOG";
  static REQUEST_EFFECTBOX_OPEN_DIALOG = "RETWE_REQUEST_EFFECTBOX_OPEN_DIALOG";
  static REQUEST_MYSTERYTROPHY_OPEN_DIALOG = "RETWE_REQUEST_MYSTERYTROPHY_OPEN_DIALOG";
  static REQUEST_ACHIEVEMENT_RESOLUTION_ENGRAVING = "RETWE_REQUEST_ACHIEVEMENT_RESOLUTION_ENGRAVING";
  static REQUEST_ACHIEVEMENT_RESOLUTION_FAILED = "RETWE_REQUEST_ACHIEVEMENT_RESOLUTION_FAILED";
  static REQUEST_FRIEND_FURNITURE_CONFIRM = "RETWE_REQUEST_FRIEND_FURNITURE_CONFIRM";
  static REQUEST_FRIEND_FURNITURE_ENGRAVING = "RETWE_REQUEST_FRIEND_FURNITURE_ENGRAVING";
  static REQUEST_BADGE_DISPLAY_ENGRAVING = "RETWE_REQUEST_BADGE_DISPLAY_ENGRAVING";
  static REQUEST_HIGH_SCORE_DISPLAY = "RETWE_REQUEST_HIGH_SCORE_DISPLAY";
  static REQUEST_HIDE_HIGH_SCORE_DISPLAY = "RETWE_REQUEST_HIDE_HIGH_SCORE_DISPLAY";
  static REQUEST_INTERNAL_LINK = "RETWE_REQUEST_INTERNAL_LINK";
  static REQUEST_ROOM_LINK = "RETWE_REQUEST_ROOM_LINK";
  get widget() {
    return this.var_45;
  }
  get contextMenu() {
    return this.var_45;
  }
}
