// Extracted from HabboAirLauncher.deobf.js, line 158808.
// Matches AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/navigator/events/HabboNavigatorTrackingEvent.as
// Obfuscated name: _ic0e5fe835a73dc

class {
  static {
    n(this, "HabboNavigatorTrackingEvent");
  }
  static HABBO_NAVIGATOR_TRACKING_EVENT_CATEGORIES = "HABBO_NAVIGATOR_TRACKING_EVENT_CATEGORIES";
  static HABBO_NAVIGATOR_TRACKING_EVENT_CLOSED = "HABBO_NAVIGATOR_TRACKING_EVENT_CLOSED";
  static HABBO_NAVIGATOR_TRACKING_EVENT_EVENTS = "HABBO_NAVIGATOR_TRACKING_EVENT_EVENTS";
  static HABBO_NAVIGATOR_TRACKING_EVENT_ME = "HABBO_NAVIGATOR_TRACKING_EVENT_ME";
  static HABBO_NAVIGATOR_TRACKING_EVENT_OFFICIAL = "HABBO_NAVIGATOR_TRACKING_EVENT_OFFICIAL";
  static HABBO_NAVIGATOR_TRACKING_EVENT_ROOMS = "HABBO_NAVIGATOR_TRACKING_EVENT_ROOMS";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCH = "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCH";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FAVOURITES =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FAVOURITES";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FREQUENT_HISTORY =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FREQUENT_HISTORY";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FRIENDS_ROOMS =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_FRIENDS_ROOMS";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_HISTORY =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_HISTORY";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_ROOMS =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_MY_ROOMS";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_OFFICIALROOMS =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_OFFICIALROOMS";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_POPULAR_ROOMS =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_POPULAR_ROOMS";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WHERE_MY_FRIENDS_ARE =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WHERE_MY_FRIENDS_ARE";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WITH_HIGHEST_SCORE =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_ROOMS_WITH_HIGHEST_SCORE";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TAG_SEARCH =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TAG_SEARCH";
  static HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TEXT_SEARCH =
    "HABBO_NAVIGATOR_TRACKING_EVENT_SEARCHTYPE_TEXT_SEARCH";
}
