// Estratto da HabboAirLauncher.deobf.js, riga 159844.
// Corrisponde a AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/ui/widget/enums/RoomWidgetEnum.as
// Nome offuscato: _i019c43eb45a743

class {
  static {
    n(this, "RoomWidgetEnum");
  }
  static AREA_HIDE = "RWE_AREA_HIDE";
  static AVATAR_INFO = "RWE_AVATAR_INFO";
  static CAMERA = "RWE_CAMERA";
  static CHAT_INPUT_WIDGET = "RWE_CHAT_INPUT_WIDGET";
  static _rac92b01a16599e = "RWE_CHAT_WIDGET";
  static CLOTHING_CHANGE = "RWE_CLOTHING_CHANGE";
  static CONVERSION_TRACKING = "RWE_CONVERSION_TRACKING";
  static CRAFTING = "RWE_CRAFTING";
  static CUSTOM_STACK_HEIGHT = "RWE_CUSTOM_STACK_HEIGHT";
  static CUSTOM_USER_NOTIFICATION = "RWE_CUSTOM_USER_NOTIFICATION";
  static DIMMER = "RWE_ROOM_DIMMER";
  static DOORBELL = "RWE_DOORBELL";
  static const_65 = "RWE_EFFECTS";
  static EXTERNAL_IMAGE = "RWE_EXTERNAL_IMAGE";
  static FRIEND_FURNI_CONFIRM = "RWE_FRIEND_FURNI_CONFIRM";
  static FRIEND_FURNI_ENGRAVING = "RWE_FRIEND_FURNI_ENGRAVING";
  static FRIEND_REQUEST = "RWE_FRIEND_REQUEST";
  static FRIENDS_BAR = "RWE_FRIENDS_BAR";
  static FURNI_ACHIEVEMENT_RESOLUTION_ENGRAVING = "RWE_FURNI_ACHIEVEMENT_RESOLUTION_ENGRAVING";
  static FURNI_CHOOSER = "RWE_FURNI_CHOOSER";
  static FURNI_CREDIT_WIDGET = "RWE_FURNI_CREDIT_WIDGET";
  static FURNI_ECOTRONBOX_WIDGET = "RWE_FURNI_ECOTRONBOX_WIDGET";
  static FURNI_PET_PACKAGE_WIDGET = "RWE_FURNI_PET_PACKAGE_WIDGET";
  static FURNI_PLACEHOLDER_WIDGET = "RWE_FURNI_PLACEHOLDER";
  static FURNI_PRESENT_WIDGET = "RWE_FURNI_PRESENT_WIDGET";
  static FURNI_STICKIE_WIDGET = "RWE_FURNI_STICKIE_WIDGET";
  static FURNI_TROPHY_WIDGET = "RWE_FURNI_TROPHY_WIDGET";
  static FURNITURE_CONTEXT_MENU = "RWE_FURNITURE_CONTEXT_MENU";
  static const_121 = "RWE_HIGH_SCORE_DISPLAY";
  static INFOSTAND_WIDGET = "RWE_INFOSTAND";
  static INTERNAL_LINK = "RWE_INTERNAL_LINK";
  static LOADINGBAR = "RWE_LOADINGBAR";
  static LOCATION_WIDGET = "RWE_LOCATION_WIDGET";
  static MANNEQUIN = "RWE_MANNEQUIN";
  static ME_MENU_WIDGET = "RWE_ME_MENU";
  static PLAYLIST_EDITOR_WIDGET = "RWE_PLAYLIST_EDITOR_WIDGET";
  static POLL = "RWE_ROOM_POLL";
  static const_1220 = "RWE_PURSE_WIDGET";
  static RENTABLESPACE = "RWE_RENTABLESPACE";
  static ROOM_BACKGROUND_COLOR = "RWE_ROOM_BACKGROUND_COLOR";
  static ROOM_LINK = "RWE_ROOM_LINK";
  static ROOM_QUEUE = "RWE_ROOM_QUEUE";
  static ROOM_THUMBNAIL_CAMERA = "RWE_ROOM_THUMBNAIL_CAMERA";
  static ROOM_TOOLS = "RWE_ROOM_TOOLS";
  static SPAMWALL_POSTIT_WIDGET = "RWE_SPAMWALL_POSTIT_WIDGET";
  static const_1077 = "RWE_UI_HELP_BUBBLE";
  static USER_CHOOSER = "RWE_USER_CHOOSER";
  static USER_NOTIFICATION = "RWE_USER_NOTIFICATION";
  static VIMEO = "RWE_VIMEO";
  static const_328 = "RWE_WORD_QUIZZ";
  static YOUTUBE = "RWE_YOUTUBE";
}
