// Extracted from HabboAirLauncher.deobf.js, line 158606.
// Matches AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/friendlist/events/HabboFriendListTrackingEvent.as
// Obfuscated name: _i8de99593910eed

class {
  static {
    n(this, "HabboFriendListTrackingEvent");
  }
  static HABBO_FRIENDLIST_TRACKING_EVENT_CLOSED = "HABBO_FRIENDLIST_TRACKING_EVENT_CLOSED";
  static HABBO_FRIENDLIST_TRACKING_EVENT_FRIENDS = "HABBO_FRIENDLIST_TRACKING_EVENT_FRIENDS";
  static HABBO_FRIENDLIST_TRACKING_EVENT_MESSENGER = "HABBO_FRIENDLIST_TRACKING_EVENT_MESSENGER";
  static const_649 = "HABBO_FRIENDLIST_TRACKING_EVENT_MINIMZED";
  static HABBO_FRIENDLIST_TRACKING_EVENT_REQUEST = "HABBO_FRIENDLIST_TRACKING_EVENT_REQUEST";
  static HABBO_FRIENDLIST_TRACKING_EVENT_SEARCH = "HABBO_FRIENDLIST_TRACKING_EVENT_SEARCH";
}
