// Extracted from HabboAirLauncher.deobf.js, line 144120.
// Matches AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/catalog/event/CatalogEvent.as
// Obfuscated name: _iadac0fa58eb9b6

class extends M {
  static {
    n(this, "CatalogEvent");
  }
  static CATALOG_BUILDER_MEMBERSHIP_EXPIRED = "CATALOG_BUILDER_MEMBERSHIP_EXPIRED";
  static CATALOG_BUILDER_MEMBERSHIP_IN_GRACE = "CATALOG_BUILDER_MEMBERSHIP_IN_GRACE";
  static CATALOG_INITIALIZED = "CATALOG_INITIALIZED";
  static CATALOG_INVISIBLE_PAGE_VISITED = "CATALOG_INVISIBLE_PAGE_VISITED";
  static CATALOG_NEW_ITEMS_HIDE = "CATALOG_NEW_ITEMS_HIDE";
  static CATALOG_NEW_ITEMS_SHOW = "CATALOG_NEW_ITEMS_SHOW";
  static CATALOG_NOT_READY = "CATALOG_NOT_READY";
  static CATALOG_USER_SELECTED = "CATALOG_USER_SELECTED";
  static COLLECTIBLES_CLAIM_FAIL = "COLLECTIBLES_CLAIM_FAIL";
  static COLLECTIBLES_CLAIM_SUCCESS = "COLLECTIBLE_CLAIM_SUCCESS";
  static COLLECTIBLES_CLAIM_WAIT = "COLLECTIBLE_CLAIM_WAIT";
  static COLLECTIBLES_MINT_FAIL = "COLLECTIBLES_MINT_FAIL";
  static COLLECTIBLES_MINT_SUCCESS = "COLLECTIBLES_MINT_SUCCESS";
  constructor(...e) {
    super(...e);
  }
}
