"""Writes a README.md in every area of the per-class tree (com/sulake/<x>/<y>), plus an
index at its root and in _unmatched/ and _runtime_and_libraries/.

usage: python area_readmes.py <05_sorgenti_per_classe> <06_report>
Run from the tools directory after protocol.py."""
import json, os, re, sys
from collections import Counter, defaultdict

ROOT, REP = sys.argv[1], sys.argv[2]
PROTO = json.load(open(os.path.join(REP, 'protocol.json'), encoding='utf-8'))
OBF = re.compile(r'^(class|package)_\d+')

def js_files(d):
    for dp, _, fs in os.walk(d):
        for f in fs:
            if f.endswith('.js'): yield os.path.join(dp, f)

def info(path):
    txt = open(path, encoding='utf-8').read()
    members = len(re.findall(r'^\s{2,4}(?:static\s+)?(?:get |set |async )?[\w$#]+\s*(?:\(|=|;)', txt, re.M))
    ext = re.search(r'class(?:\s+\w+)?\s+extends\s+([\w$]+)', txt)
    kind = ('event' if ext and ext.group(1) == 'MessageEvent' else
            'composer' if 'getMessageArray()' in txt else
            'parser' if re.search(r'^\s+parse\(\w+\)', txt, re.M) and 'flush()' in txt else '')
    return dict(lines=txt.count('\n'), members=members, ext=ext.group(1) if ext else '', kind=kind)

def area_of(src):
    parts = src.split('/')
    return '/'.join(parts[:4]) if src.startswith('com/sulake/') else parts[0]

# a message belongs to the areas of the classes that create it (event handlers, senders)
JS = json.load(open('work/js.json', encoding='utf-8'))
NM = json.load(open(os.path.join(REP, 'name_map.json'), encoding='utf-8'))
path_of = {c['binding']: NM['paths'].get(c['name'] or c['binding']) for c in JS if c['binding']}
users = defaultdict(set)
for b, enc, _ in json.load(open('work/js_news.json', encoding='utf-8')):
    p = path_of.get(enc)
    if p and p.startswith('com/'): users[b].add(area_of(p))
msgs = defaultdict(list)
for r in PROTO:
    for a in users.get(r.get('binding'), ()): msgs[a].append(r)

def table(rows, heads):
    return '\n'.join(['| ' + ' | '.join(heads) + ' |', '|' + '---|' * len(heads)] +
                     ['| ' + ' | '.join(str(c).replace('|', '\\|') for c in r) + ' |' for r in rows])

areas = sorted({'/'.join(os.path.relpath(os.path.dirname(f), ROOT).replace(os.sep, '/').split('/')[:4])
                for f in js_files(os.path.join(ROOT, 'com'))})
areas = [a for a in areas if a.count('/') == 3]
index = []
for a in areas:
    d = os.path.join(ROOT, a)
    files = list(js_files(d))
    rel = lambda f: os.path.relpath(f, d).replace(os.sep, '/')
    infos = {rel(f): info(f) for f in files}
    kinds = Counter(i['kind'] for i in infos.values())
    subs = Counter(rel(f).split('/')[0] if '/' in rel(f) else '.' for f in files)
    named = [(n, i) for n, i in infos.items() if not OBF.match(os.path.basename(n)) and not i['kind']]
    named.sort(key=lambda x: -x[1]['lines'])
    L = [f'# `{a}`\n', 'Generated by `tools/area_readmes.py`. Class names come from the AIR 15 match; '
         '`class_N` names are AIR 15 FFDec labels.\n',
         '| | |\n|---|---|', f'| Classes | {len(files)} |',
         f"| Message events / parsers / composers | {kinds['event']} / {kinds['parser']} / {kinds['composer']} |",
         f'| Lines of code | {sum(i["lines"] for i in infos.values()):,} |\n']
    if len(subs) > 1:
        L += ['## Sub-packages\n', table([(f'[`{s}`]({s}/)' if s != '.' else '(this folder)', n) for s, n in sorted(subs.items())], ['Package', 'Classes']), '']
    if named:
        L += ['## Main classes\n', 'The largest classes with a real name, by size.\n',
              table([(f'[`{os.path.basename(n)[:-3]}`]({n})', i['ext'] if len(i['ext']) > 3 else '', i['members'], i['lines']) for n, i in named[:30]],
                    ['Class', 'Extends', 'Members', 'Lines']), '']
    m = list({(r['direction'], r['header']): r for r in msgs.get(a, [])}.values())
    if m:
        inc = sorted((r for r in m if r['direction'] == 'incoming'), key=lambda r: r['header'])
        out = sorted((r for r in m if r['direction'] == 'outgoing'), key=lambda r: r['header'])
        L += ['## Network messages\n', 'Messages created or registered by classes of this area. Header IDs are those of this build; full table in `06_report/PROTOCOL.md`.\n']
        if inc:
            L += ['### Incoming\n', table([(r['header'], f"`{r['name']}`", f"`{r.get('parser', '')}`", (r.get('structure') or '')[:140]) for r in inc],
                                          ['ID', 'Event', 'Parser', 'Structure']), '']
        if out:
            L += ['### Outgoing\n', table([(r['header'], f"`{r['name']}`", r.get('args', ''), r.get('air15_arg_types', '')) for r in out],
                                          ['ID', 'Composer', 'Args', 'AIR 15 arg types']), '']
    open(os.path.join(d, 'README.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    mm = msgs.get(a, [])
    index.append((a, len(files), len({r['header'] for r in mm if r['direction'] == 'incoming'}), len({r['header'] for r in mm if r['direction'] == 'outgoing'})))

def count_dir(n): return sum(1 for _ in js_files(os.path.join(ROOT, n))) if os.path.isdir(os.path.join(ROOT, n)) else 0
pk = sorted(x for x in os.listdir(ROOT) if x.startswith('package_'))
L = ['# Per-class sources\n', 'One file per class of the client, placed at the path of the matching AIR 15 AS3 source. '
     'Each file starts with a header naming its line in `04_sorgenti_js/HabboAirLauncher.deobf.js`, '
     'the AIR 15 source and the original obfuscated name.\n', '## Areas\n',
     table([(f'[`{a}`]({a}/)', n, e, c) for a, n, e, c in index], ['Area', 'Classes', 'Incoming messages', 'Outgoing messages']), '',
     '## Other folders\n',
     table([('`package_N/`', f'{sum(count_dir(p) for p in pk)} classes in {len(pk)} packages that AIR 15 itself only knows by FFDec label'),
            ('[`_unmatched/`](_unmatched/)', f"{count_dir('_unmatched')} classes with no AIR 15 match, under `Unk…` placeholder names"),
            ('[`_runtime_and_libraries/`](_runtime_and_libraries/)', f"{count_dir('_runtime_and_libraries')} readable-name classes not in AS3: Pixi.js and the Flash emulation layer")],
           ['Folder', 'Content']), '']
open(os.path.join(ROOT, 'README.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')

# _unmatched: grouped by placeholder pattern
d = os.path.join(ROOT, '_unmatched')
groups = Counter(re.sub(r'_[0-9a-f]{6}_*$|_\w+$', '', f[:-3]) if f.startswith('UnkMessage') else re.sub(r'_[0-9a-f]{6}_*$', '', f[:-3])
                 for f in os.listdir(d) if f.endswith('.js'))
L = ['# Unmatched classes\n', 'Hashed classes for which no AIR 15 counterpart was found. Their names are placeholders '
     'built from their shape (see "Naming conventions" in the repository README); the original obfuscated name is in each '
     "file's header. Many are classes rewritten by the port, not new features.\n",
     table(sorted(groups.items(), key=lambda x: -x[1]), ['Pattern', 'Classes']), '']
open(os.path.join(d, 'README.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')

d = os.path.join(ROOT, '_runtime_and_libraries')
names = sorted(f[:-3] for f in os.listdir(d) if f.endswith('.js'))
L = ['# Runtime and libraries\n', 'Classes that kept a readable name but do not exist in the AS3 client: Pixi.js '
     '(renderers, pipes, systems, geometry) and the layer that emulates the Flash API on top of it '
     '(`Sprite`, `BitmapData`, `Matrix`, `Air32NativeTextRenderer`, …).\n', ', '.join(f'[`{n}`]({n}.js)' for n in names), '']
open(os.path.join(d, 'README.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('area READMEs', len(areas))
