"""Writes CHANGES_REPORT.md: a data-driven comparison of this build against the AIR 15
reference and, optionally, against a previous output of this pipeline.

usage: python changes.py <out_dir> [<previous_out_dir>]
Run from the tools directory, after match.py, finalize.py and protocol.py."""
import json, re, sys, os
from collections import Counter

OUT = sys.argv[1]
PREV = sys.argv[2] if len(sys.argv) > 2 else None
JS = json.load(open('work/js.json', encoding='utf-8'))
AS3 = json.load(open('work/as3.json', encoding='utf-8'))
FM = json.load(open('work/final_map.json', encoding='utf-8'))
PROTO = json.load(open(os.path.join(OUT, '06_report', 'protocol.json'), encoding='utf-8'))
HASH_C = re.compile(r'^_i[0-9a-f]{14}$')
app = os.path.join(OUT, '02_app_estratto')

def load(p, default=None):
    try: return json.load(open(p, encoding='utf-8'))
    except OSError: return default
pkg = load(os.path.join(app, 'package.json'), {})
rel = load(os.path.join(app, 'client', 'release-manifest.json'), {})
info = load(os.path.join(app, 'client', 'habbo-air', 'launcher-build-info.json'), {})

# functional strings of the Habbo code that AIR 15 does not have
as3_str = {s for c in AS3 for s in c['strings']} | {m['val'].strip('"') for c in AS3 for m in c['members'] if m.get('val')}
KEY = re.compile(r'^\$?\{?[a-z0-9_]+(\.[a-z0-9_\-]+)+\}?$')
URL = re.compile(r'(https?://|wss?://|^/[\w\-/]+$|://)')
keys, urls = {}, {}
for c in JS:
    if not (c['name'] and (HASH_C.match(c['name']) or c['name'] in FM['as3_for'])): continue
    owner = FM['classes'].get(c['name'], c['name'])
    for s in c['strings']:
        if s in as3_str or HASH_C.match(s): continue
        if KEY.match(s): keys.setdefault(s, set()).add(owner)
        elif URL.search(s) and len(s) < 120: urls.setdefault(s, set()).add(owner)

as3_names = {c['name'] for c in AS3}
new_named = sorted({c['name'] for c in JS if c['name'] and not HASH_C.match(c['name']) and c['name'] not in as3_names})

used = set(FM['as3_for'].values())
area = Counter(); hit = Counter()
for c in AS3:
    f = c['file']
    if f.startswith('package_'): continue
    p = '/'.join(f.split('/')[:4]) if f.startswith('com/sulake/habbo/') else '/'.join(f.split('/')[:3])
    area[p] += 1; hit[p] += f in used

ev = [r for r in PROTO if r['direction'] == 'incoming']; co = [r for r in PROTO if r['direction'] == 'outgoing']
L = []
L.append('# Changes report\n')
L.append('Generated by `tools/changes.py`. Every item is taken from the code; nothing here says whether a feature is enabled on the server.\n')
L.append('## Build\n')
L.append('| | Value |\n|---|---|')
L.append(f"| Release | `{rel.get('releaseId', '?')}` |")
L.append(f"| App | `{pkg.get('name', '?')}` {pkg.get('version', '?')} |")
L.append(f"| Protocol | `{rel.get('protocol', '?')}` |")
L.append(f"| Built at (ms) | {info.get('builtAtMs', '?')} |")
L.append(f"| Classes in the bundle | {len(JS)} |")
L.append(f"| Classes matched to AIR 15 | {len(FM['as3_for'])} |")
L.append(f"| Member names recovered | {len(FM['members'])} |")
L.append(f"| Incoming / outgoing messages | {len(ev)} / {len(co)} |\n")
L.append('## Readable-name classes not in AIR 15\n')
L.append('Mostly runtime and library code (Pixi.js, Flash emulation); the few client classes stand out by name.\n')
L.append(', '.join(f'`{n}`' for n in new_named) + '\n')
L.append(f'## Configuration and localization keys not in AIR 15 ({len(keys)})\n')
L.append('| Key | Used in |\n|---|---|')
for k in sorted(keys): L.append(f"| `{k}` | {', '.join(sorted(keys[k]))[:160]} |")
L.append(f'\n## URLs and paths not in AIR 15 ({len(urls)})\n')
L.append('| String | Used in |\n|---|---|')
for k in sorted(urls): L.append(f"| `{k}` | {', '.join(sorted(urls[k]))[:160]} |")
L.append('\n## Match coverage by area\n')
L.append('A low share means the port rewrote more there, or the classes are too small to recognize; it does not mean the feature is gone.\n')
L.append('| Area | Matched |\n|---|---|')
for p, t in sorted(area.items(), key=lambda x: -x[1]):
    if t >= 15: L.append(f'| `{p}` | {hit[p]} / {t} ({hit[p] / t:.0%}) |')

if PREV:
    pp = load(os.path.join(PREV, '06_report', 'protocol.json'), [])
    pm = load(os.path.join(PREV, '06_report', 'name_map.json'), {})
    L.append('\n## Compared with the previous build\n')
    def names(rs, d): return {r['name'] for r in rs if r['direction'] == d and not r['name'].startswith('Unk')}
    for d in ('incoming', 'outgoing'):
        a, b = names(pp, d), names(PROTO, d)
        L.append(f'### {d.capitalize()} messages\n')
        L.append(f'- added: {", ".join(f"`{x}`" for x in sorted(b - a)) or "none"}')
        L.append(f'- removed: {", ".join(f"`{x}`" for x in sorted(a - b)) or "none"}\n')
        idp = {r['name']: r['header'] for r in pp if r['direction'] == d}
        moved = sum(1 for r in PROTO if r['direction'] == d and r['name'] in idp and idp[r['name']] != r['header'])
        L.append(f'- header IDs changed for {moved} of {len(b & a)} messages present in both\n')
    a = set(pm.get('as3_for', {}).values()); b = set(FM['as3_for'].values())
    L.append(f'### AIR 15 classes matched\n\n- newly matched: {len(b - a)}\n- no longer matched: {len(a - b)}\n')
    if a - b:
        L.append('No longer matched (a class missing here may have been removed, or only changed enough to escape matching):\n')
        L.append(', '.join(f'`{x}`' for x in sorted(a - b)[:300]) + '\n')

open(os.path.join(OUT, 'CHANGES_REPORT.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('CHANGES_REPORT.md written:', len(keys), 'new keys,', len(urls), 'new urls,', len(new_named), 'new named classes')
