// Extracted from HabboAirLauncher.deobf.js, line 150737.
// Matches AIR 15: 03_sorgenti_e_asset/HabboAir/scripts/com/sulake/habbo/inventory/events/HabboInventoryTrackingEvent.as
// Obfuscated name: _id794d52b298f18

class {
  static {
    n(this, "HabboInventoryTrackingEvent");
  }
  static HABBO_INVENTORY_TRACKING_EVENT_ACHIEVEMENTS = "HABBO_INVENTORY_TRACKING_EVENT_ACHIEVEMENTS";
  static HABBO_INVENTORY_TRACKING_EVENT_BADGES = "HABBO_INVENTORY_TRACKING_EVENT_BADGES";
  static HABBO_INVENTORY_TRACKING_EVENT_BOTS = "HABBO_INVENTORY_TRACKING_EVENT_BOTS";
  static HABBO_INVENTORY_TRACKING_EVENT_CLOSED = "HABBO_INVENTORY_TRACKING_EVENT_CLOSED";
  static HABBO_INVENTORY_TRACKING_EVENT_COLLECTIBLES = "HABBO_INVENTORY_TRACKING_EVENT_COLLECTIBLES";
  static HABBO_INVENTORY_TRACKING_EVENT_FURNI = "HABBO_INVENTORY_TRACKING_EVENT_FURNI";
  static HABBO_INVENTORY_TRACKING_EVENT_PETS = "HABBO_INVENTORY_TRACKING_EVENT_PETS";
  static HABBO_INVENTORY_TRACKING_EVENT_POSTERS = "HABBO_INVENTORY_TRACKING_EVENT_POSTERS";
  static HABBO_INVENTORY_TRACKING_EVENT_TRADING = "HABBO_INVENTORY_TRACKING_EVENT_TRADING";
}
